name: cyasar_mobil_app

description: A Flutter application for visually impaired users, providing sign language guidance and customer service connectivity.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  url_launcher: ^6.1.7
  animate_do: ^3.3.9
  video_player: ^2.9.2
  chewie: ^1.7.4
  flutter_tts: ^3.6.3  # Metin okuma için ekledim
  flutter_webrtc: ^0.12.10 #webrtc icin
  web_socket_channel: ^2.1.0  #web socket icin

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/n11.jpg
    - assets/trendyol.png
    - assets/aliexpress.jpeg
    - assets/sign_language_guide.mp4
